### ISSUE TITLE
specifying different mafft options in OMM_MACSE

### ISSUE THREAD

**Issue by aguang** [ranwez/MACSE_V2_PIPELINES#1]
Is there a way to provide different mafft options (or MUSCLE, or any of the other aligners) in OMM_MACSE besides the one it uses? For example, if I wanted to [include `--adjustdirection`](https://mafft.cbrc.jp/alignment/software/adjustdirection.html).

**Comment by ranwez** [comment]
Hi,
you can do this using using the --aligner_extra_option parameter of the OMM_MACSE pipeline. The pipeline options are listed when executing the pipeline without any parameter and documented here [https://bioweb.supagro.inra.fr/macse/index.php?menu=docPipeline/docPipelineHtml](https://bioweb.supagro.inra.fr/macse/index.php?menu=docPipeline/docPipelineHtml). If you encounter any difficulties when using these pipelines do not hesitate to contact me.

**Comment by aguang** [comment]
Thank you, this worked.
