### ISSUE TITLE
Can't seem to find the .sif file

### ISSUE THREAD

**Issue by ahmedelbassiouny** [ranwez/MACSE_V2_PIPELINES#6]
I am a total newbie to singularity, but I was trying to follow the instructions in the 2020 paper, and it refers to using .sif file with singularity (for example, singularity run ./container.sif) but none of the files are .sif. Am I missing something? The .def files have different format for singularity. Thanks for any clarification.

**Comment by ahmedelbassiouny** [comment]
Never mind, I found the sylabs and all the .sif versions. Thanks anyway.

**Comment by RSchley** [comment]
Where are they? I also can't find them. Thanks a lot.
