### ISSUE TITLE
How to specify the reading frame in MACSE

### ISSUE THREAD

**Issue by Hassan-1991** [ranwez/MACSE_V2_PIPELINES#8]
Dear Concern,

Sometimes MACSE ignores the reading frame of the original protein sequence provided, and introduces frameshifts in the beginning. Is there a way of getting around that? How can I tell the program to consider the first base to be where the first codon starts?

Thanks and best regards,
Hassan

**Comment by ranwez** [comment]
Dear Hassan,

Thank you for your inquiry regarding MACSE. MACSE is specifically designed to switch from one reading frame to another with a penalty to accommodate potential errors such as sequencing and annotation errors within CDS and pseudogenes.

However, MACSE may sometimes fail to determine the correct reading frames, this is especially true when aligning too few sequences. In cases where you are confident that some sequences do not contain frameshifts, you may use a high frameshift penalty to prevent frameshifts within those sequences, thus forcing MACSE to adhere to the first reading frame.

To do this, you will need to provide two fasta files - one containing the reliable sequences (using the option -seq), and another containing the less reliable sequences (-seq_lr) that are more likely to contain frameshifts. You can then adjust frameshift costs within reliable sequences (-fs) at the extremity of reliable sequences (-fs_term), and within less reliable sequences (-fs_lr) at the extremities of less reliable sequences (-fs_lr_term). MACSE help provides the default values for these options, using something like -fs 1000 -fs_term 1000 would prevent the insertion of frameshifts in the reliable sequences.

I hope this information will assist you in solving your problem. If you encounter any issues, please do not hesitate to send me one of the fasta files you are attempting to align, along with a brief description of the problem, and I will do my best to help you using MACSE.

Sincerely,

**Comment by Hassan-1991** [comment]
Thanks so much for the reply! I ended up going for that exact solution - down to the precise values for -fs and -fs_term penalties. It's nice to know that's the right way forward!
