### ISSUE TITLE
handling of degenerate nucleotides in amino acid and nucleotide output files

### ISSUE THREAD

**Issue by csgenomics-admin** [ranwez/MACSE_V2_PIPELINES#9]
In the second section of the [documentation regarding genetic codes](https://www.agap-ge2pop.org/genetic-codes/), it is clear that when a degenerate nucleotide character would encode the same amino acid character, MACSE will by default translate this into the expected amino acid residue:
> When a codon contains a single ambiguous nucleotide (e.g. N, R, Y) and all its possible translation lead to the same amino acid, MACSE uses this unambiguous translation despite the nucleotide ambiguity

My error concerns a related, but different concern, in which certain, *but not all* degenerate nucleotide characters are modified in the output nucleotide alignment file. For example, consider a file (called `in.fna`) containing just two-sample input of DNA characters, in which the second sample has a series of degenerate bases in certain codons:

```
>Sample1
ATGGCCCAAATCTCCTAA
>Sample2
ATGGCKSARATHTCRTAA
```

then run MACSE's `alignSequences` program:
```
java -jar macse.jar -prog alignSequences -seq in.fna -out_AA out.faa -out_NT out.fna
```

In `Sample2`, we have four different codons with one or more degenerate bases to consider:
- second codon: `GCK`. This is a 4-way degenerate site for Alanine, thus if staying true to MACSE's intentions as noted in their documentation, this should be translated into Alanine.
- third codon: `SAR`. Unlike the second codon, this could be translated into either Gln or Glu, thus I would expect MACSE to translate this as "X", because there is more than one amino acid possible among the four possible ways to create this codon (CAA, CAG; GAA, GAG). 
- fourth codon: `ATH`. This is a 3-way degenerate site, all encoding the same amino acid - Isoleucine. I would expect MACSE to translate this codon.
- fifth codon: `TCR`. Similar to the second codon, this is a 4-way degenerate base for Serine. In fact, this codon is the codon used in the MACSE documentation as an example of how a degenerate base might be translated.

Here is the translated amino acid output alignment (file `out.faa`):
```
>Sample1
MAQIS*
>Sample2
MAXXS*
```
I find that:
1. The second (`GCK`) and fifth (`TCR`) codons are translated as expected, in that they retain the expected amino acid despite having a degenerate base.
2. The third amino acid is given an ambiguous amino acid character (`X`) as expected, because there were multiple possible amino acids possible given the degenerate nucleotide input characters.
3. I'm unclear why the fourth codon, (`ATH`) is not translated to the expected amino acid `I`. The degenerate `H` nucleotide character should produce an unambiguous codon that translates to isoleucine, but this does not appear to be the case.

**Question 1**
I would like to understand why `ATH` is not translated to `I` in this amino acid output alignment.

Next, if I review the aligned nucleotide output alignment (file `out.fna`), I notice that some, but not all of the degenerate nucleotides are masked. This was unexpected to me, because I could not find any documentation in MACSE that noted that nucleotide character states may change between input and output files (while understanding that additional characters like gaps and frameshifts may be introduced):
```
>Sample1
ATGGCCCAAATCTCCTAA
>Sample2
ATGGCNNARATNTCRTAA
```

To compare the input and output nucleotide sequences for `Sample2` for easier viewing, I've lined up the input and output sequences and denoted with a `|` symbol where the input degenerate codon was swapped for an ambiguous nucleotide character, `N`:
```
                 .M..A..X..I..S..*.
Sample2-input:   ATGGCKSARATHTCRTAA
                      ||    |
Sample2-output:  ATGGCNNARATNTCRTAA
```

**Question(s) 2**
2a. I would have thought that no degenerate codons would be replaced by `N` in the output nucleotide alignment. Is there documentation stating that this is the expected behavior?
2b. I would have predicted that, if degenerate bases were masked, then _ALL_ degenerate bases would be swapped. But this is clearly not the case. Is there a rule that can predict when this would or would not occur?
2c. Given the fact that the second codon is currently translated (as Alanine) with MACSE, I would have thought that the degenerate bases in that codon would not be masked. However, it appears that the `K` in `GCK` is indeed masked, despite that codon being properly translated. Is this expected?
2d. Given the fact that the third codon is NOT unambiguously translated, I would have thought that the degenerate bases may be masked _because the aligned amino acid for that codon is `X`_. However, this is only true for one, but not both, of the degenerate codons in this position (the `S`, but not `R`, in `SAR`. Is this the expected behavior?

**Comment by ranwez** [comment]
Thank you for taking time to produce this very detail bug report with a minimal example, this definitively help me to understand what is going on.

The problem is that the documentation is misleading and seems to indicate that MACSE handle all [ambiguity IUPAC codes](https://fr.wikipedia.org/wiki/Nucléotide). This is not the case, and the current version of MACSE only handle the most frequent ambiguity codes R (A/G) Y (C/T) and N(A/C/G/T). All letters appearing in the sequence which are different from ACGTRY acgtry are considered as unknown nucleotide N.

Therefore your ambigous sequence is read/considered by MACSE as follow
```
>Sample2
(original) ATGGCKSARATHTCRTAA
(macse)    ATGGCNNARATNTCRTAA
```
To keep track of this, we indeed output the version of this sequence considered by MACSE in the out_NT.fasta file (which explain why only nucleotides, not codon, are "masked").

And the translation of this sequence (in the first reading frame with the standart genetic code) is:
```
ATG GCN NAR ATN TCR TAA
 M   A   X   X   S   *                
```

Thanks for spotting this error in error in MACSE documentation, I will fix it and point to this discussion to clarify how MACSE handle ambiguity codes. I'm sorry for the inconvenience and I hope this clarify what is done by MACSE.

I don't have much feedbacks regarding code ambiguity so I don't know if it is worth extending MACSE to better handle it...

**Comment by csgenomics-admin** [comment]
Thanks @ranwez for the response.  

I'm curious what data was used to identify `R` and `Y` as the most frequent degenerate nucleotide characters (I think of `N` as a different kind of character, one that is not degenerate, but truly _ambiguous_). In my experience, the frequency of a degenerate character is driven uniquely by the pipeline and data, and is not necessarily a kind of universal. Perhaps you encountered these two particular degenerate characters based on your work with COI?  

Updating the documentation to clarify which degenerate characters are supported is definitely helpful, but I would also like to know whether or not it is possible to have the output nucleotide alignment file remain unchanged from the original character inputs. That is, if I input a string that contains an R or Y, should MACSE be able to translate that degenerate character, do *not* change that R or Y to an N in the output.

In my example above, what is currently happening between the input and output nucleotide string looks like this:
```
>Sample2
(-seq input)        ATGGCKSARATHTCRTAA
(-out_NT output)    ATGGCNNARATNTCRTAA
```

What I would prefer is that it looks like this (nothing changes!):
```
>Sample2
(-seq input)        ATGGCKSARATHTCRTAA
(-out_NT output)    ATGGCKSARATHTCRTAA
```

Making these silent R/Y --> N changes was breaking part of my pipeline, because I did not assume that the input and output nucleotide characters would be different (other than the insertion of new gap and/or frameshift characters). Should it not be possible to make such a change, I would recommend highlighting to the users two things about this process:
1. As you've stated already, the degenerate nucleotide substitutions are limited to a subset of possible degenerate characters.
2. In certain cases, these degenerate characters are substituted in the output nucleotide file, so the input/output strings will not necessarily match.  

Thanks for your attention, and thank you for continuing to support this terrific software.

**Comment by ranwez** [comment]
Thanks for your positive feedbask on MACSE despite the problems you are currently facing. 

R and Y are not silently changed into N they are correctly handle by MACSE but all other ambiguity codes are silently changed (I precise this just to avoid confusion for future readers). I agree that changing the sequences which are aligned is an error. I checked rapidly and I cannot easily fix this in the current release of MACSE. The first version of MACSE was very memory demanding at one point I thus compress nucleotides to handle them in three bits without preserving the original character (not my best design choice ;)

Meanwhile I can suggest a possible workaround using a script to report gaps and frameshifts of MACSE NT alignment into your initial unaligned sequences. I added a python script that does that in [this github repository] (https://github.com/ranwez/MACSE_V2_PIPELINES/tree/master/OTHER_SCRIPTS/REPORT_GAP)) with a little (stupid) example:
```
cat input_aligned_file
> seq 1
ACT---NCT
> seq2
ACTACTA!T

cat input_nonaligned.fasta
> seq 1
ACTRCT
> seq2
ACThctAT

insert_gaps.py input_aligned.fasta input_nonaligned.fasta > output.fasta

cat output.fasta
> seq 1
ACT---RCT
> seq2
ACThctA!T
'''
there is no advanced checks ensuring that sequences in both files are consistent (same names, same length once unaligned etc) so please use it cautiously.

Though not an ideal solution, including an additional step in your pipeline using this basic script should allow you to get a correct aligned version of your sequences. I will try to fix this in the next major release of MACSE but I don't know when it will be. Meanwhile I hope this workaround will allow you to analyze your data with MACSE. Do not hesitate to get in touch if you are facing any other problems.

**Comment by csgenomics-admin** [comment]
Thanks, and your solution iterating across the unaligned sequence and skipping over the gap (`-`) and frameshift `(!)` characters is a great solution. Appreciate your prompt replies :)
